### ISSUE TITLE
Need to create MSI package for Flexera ndtrack.exe

### ISSUE THREAD

**Issue by ekanodia** [pennmanor/wix-wrapper#10]
I need to create a MSI package for flexera agent in windows. I have few .dll files and ndtrack.exe. I tried modifying the nextcloud.wxs lines 2-6 and then ran make_installer.bat file. The msi is created but on double clicking, it doesnt work. How am I suppose to know if its really working or I ve missed including dll files in the package?

**Comment by cabillman** [comment]
Hi ekanodia,

This wix-wrapper project was created specifically to convert owncloud/nextcloud client exe installer to an MSI. It works by running the exe installer when the msi is deployed. 

I am not familiar with flexera but it sounds like you are trying to package the agent itself and not the installer which would be a completely different approach.

Creating an MSI from scratch is something I haven't done. If that is the required approach I would suggest reaching out to the wix community. The main website can be found here: http://wixtoolset.org/
