### ISSUE TITLE
Product GUID

### ISSUE THREAD

**Issue by darksody** [pennmanor/wix-wrapper#2]
Hi, i am looking to simplify the way a msi is created.

My first question is: the UpgradeCode, is it really used? If i wrap an exe, let's say, the vlc_installer.exe. The newly created msi will install VLC for me, but in the uninstall list of windows i can see VLC, which is normal, but not this msi. Is it self-uninstalling right after? Does that mean that i don't really need the GUIDs and i can auto-generate them?

I am looking to remove the upgrade portion, get rid of ProductUpgradeCode guid and autogenerate the ProductCode guid. I already did this and it seems to be working fine. Are there any risks i should worry about?

Thank you.

**Comment by darksody** [comment]
Also, great job on this! I find it very useful! :)

**Comment by tomswartz07** [comment]
Hi there!

Thanks for the interest. I'm glad you find it useful!

To fully understand the mechanics of each of the items, let me briefly explain how Windows manages MSI installs (as I understand it).

## In the world of Windows:
When a program is installed, it's assigned a GUID. As the name implies, it **G**lobally **U**niquely **ID**entifies the software, allowing the registry to differentiate between VLC and Firefox, even if they were both installed at nearly the same time.

When an update for the software is set to be installed (in the case of an MSI, specifically) the installer must know two things: 
1. the GUID of the 'old' version it will replace ("Am I replacing Firefox or VLC?")
2. the GUID of the new version to register itself for future updates.

This system allows you to prevent unintended 'downgrades' of the program when you have multiple versions floating about. You explicitly define your release path: Version 1 → Optional Bugfix Version 1.5 → Version 2

A neat side-effect of the GUID system is that, if you use Active Directory Group Policy deployments, you can customize how the application is upgraded.
This is to say, before installing the update you can tell the computer to either remove the old version completely or just install right over-top of the old program.
This allows for a 'fresh start' with default settings in the former case, or allows you to keep user settings and configurations in the latter.

## That all being said...
UpgradeCode is not used during a first-time install.
If you know for certain that your app will be a 'one-off' install, you could safely ignore it.
However, if you plan to release a revision that will also be deployed, the UpgradeCode is necessary.

I do believe that some programs (Visual Studio, for example) will allow you to automatically generate GUIDs: which is useful for the 'ProductCode' field, but you'd still need to manually define the 'ProductUpdateCode' field yourself.

**Comment by tomswartz07** [comment]
I should also point out: because we're 'wrapping' an `.exe` file which would have its own logic for upgrades, downgrades, etc. does not necessarily say that the program will be updated as intended. 

Some software will act as expected, but others (as I've seen) will install side-by-side versions of the program. As in, you'll have Firefox v15 and Firefox v16 installed at the same time, as two separate entries.

The ProductUpgradeCode assures that the `.msi` wrapper will remove/overwrite the previous version, no matter what the logic of the `.exe` may be.
