### ISSUE TITLE
Unable to compile (warning CNDL1091 and error CNDL0027)

### ISSUE THREAD

**Issue by crysman** [pennmanor/wix-wrapper#3]
Hello, I am unable to "compile" the owncloud installer :/

    C:\Users\crysman\Downloads>owncloud_make_installer.bat
    C:\Users\crysman\Downloads>del owncloud.msi
    Nelze najít C:\Users\crysman\Downloads\owncloud.msi.

    C:\Users\crysman\Downloads>del owncloud.wixobj
    Nelze najít C:\Users\crysman\Downloads\owncloud.wixobj.

    C:\Users\crysman\Downloads>del owncloud.wixpdb
    Nelze najít C:\Users\crysman\Downloads\owncloud.wixpdb.

    C:\Users\crysman\Downloads>candle owncloud.wxs
    Windows Installer XML Toolset Compiler version 3.9.1208.0
    Copyright (c) Outercurve Foundation. All rights reserved.

    owncloud.wxs
    C:\Users\crysman\Downloads\owncloud.wxs(14) : warning CNDL1091 : The Package/@Id
    attribute has been set.  Setting this attribute will allow nonidentical .msi fi
    les to have the same package code.  This may be a problem because the package co
    de is the primary identifier used by the installer to search for and validate th
    e correct package for a given installation.  If a package is changed without cha
    nging the package code, the installer may not use the newer package if both are
    still accessible to the installer.  Please remove the Id attribute in order to a
    utomatically generate a new package code for each new .msi file.
    C:\Users\crysman\Downloads\owncloud.wxs(23) : error CNDL0027 : The File/@Name at
    tribute's value, 'c:\users\crysman\downloads\ownCloudsetup.exe', is not a valid
    long name because it contains illegal characters.  Legal long names contain no m
    ore than 260 characters and must contain at least one non-period character.  Any
    character except for the follow may be used: \ ? | > < : / * ".

    C:\Users\crysman\Downloads>light owncloud.wixobj
    light.exe : error LGHT0103 : The system cannot find the file 'owncloud.wixobj' w
    ith type 'Source'.

**Comment by crysman** [comment]
Any help, please? Are you missing some information?

**Comment by tomswartz07** [comment]
Hi there @crysman,

Sorry for the delay: i was away on holiday.

Can you post the line for `<?define ExeSourceFile ... `?
According to the output, I think it might be 'c:\users\crysman\downloads\ownCloudsetup.exe'

It seems that WiX is tripping up on the filename.

The filename should not include the full path, it should just be the name of the `.exe`. You'll have to copy the .exe to be contained within the source code folder.

**Comment by crysman** [comment]
Sorry, I've been out of reach of the Windows machine.

YES, you were right, it needs a relative filename, not absolute, sorry for my inattention :/

Though, I would suggest to include it into that comment (that it needs just the filename, no path)

Now I am going to test the MSI :)

**Comment by crysman** [comment]
BTW, when I will upgrade to newer version (>1.8.3)... I download the new setup file, I wait for your new .WXS file, when available, I can compile new MSI and deploy in our domain. Is this correct?

You will change the `ProductCode` and `ProductUpgradeCode` accordingly in the new WXS file - is that right? Or I shall change it somehow? Thanks!

**Comment by tomswartz07** [comment]
Glad you got it sorted!
I'll push up a comment so that it's a bit more obvious to use a relative file path.

Yes- I usually get the .wxs file updated with the new product codes within the week of release.

Alternately, if you want to generate your own, just grab a [guid generator](http://www.guidgen.com/) and drop in the output in all caps.
