### ISSUE TITLE
No desktop shortcut

### ISSUE THREAD

**Issue by crysman** [pennmanor/wix-wrapper#6]
Hello Tom, please, how to customize the wxs in order to NOT get shortcut on desktop after installation? In case of owncloud, owncloud shortcut on desktop is being placed on every user's desktop - I do not want that...

Thanks!

**Comment by tomswartz07** [comment]
@crysman This shortcut install is part of the ownCloud package itself.
I took a quick look at the source for the client, but there's no obvious flag to disable this.

There are two options:
1. Add a step to your Group Policy to remove this link from the `C:\Users\Public\Desktop` folder
2. File a ticket upstream with [owncloud\client](https://github.com/owncloud/client) to see if they would add an installer flag.

I wouldn't recommend putting an extra `exec` step in the .wxs, as the client .exe might change, and the resulting .msi will fail (or worse, delete something wrong :grimacing:)

**Comment by crysman** [comment]
OK, thanks, it's there:
https://github.com/owncloud/client/issues/3949
